#!/bin/sh

[ -f kiss-vm.img ] || {
    qemu-img create -f qcow2 kiss-vm.img 16G
}

qemu-system-x86_64 \
    -enable-kvm \
    -cpu host \
    -smp 4 \
    -m 4G \
    -drive file=kiss-vm.img,if=virtio \
    -netdev user,id=vmnic,hostname=Kiss \
    -device virtio-net,netdev=vmnic \
    -device virtio-rng-pci \
    -monitor stdio \
    -boot d \
    -cdrom "$@"
