#!/bin/sh -e

# fix build failure against gcc-10
sed -i "s/struct cache \*bwriter_buffer, \*fwriter_buffer;/extern struct cache \*bwriter_buffer, \*fwriter_buffer;/g"  squashfs-tools/mksquashfs.h
cd squashfs-tools

make XZ_SUPPORT=1 LZO_SUPPORT=0 LZ4_SUPPORT=0 ZSTD_SUPPORT=0

install -Dm755 mksquashfs "$1/usr/bin/mksquashfs"
install -m755  unsquashfs "$1/usr/bin/unsquashfs"
