#!/bin/sh
#
# false positive
# shellcheck disable=2154

cdrom="/usr/lib/modules/$kernel/kernel/drivers/cdrom/cdrom.ko"
loop="/usr/lib/modules/$kernel/kernel/drivers/block/loop.ko"
overlay="/usr/lib/modules/$kernel/kernel/fs/overlayfs/overlay.ko"
squash="/usr/lib/modules/$kernel/kernel/fs/squashfs/squashfs.ko"

for _mod in "$cdrom" "$loop" "$overlay" "$squash"; do
    copy_module "$_mod"
done

copy_file /usr/lib/udev/rules.d/60-cdrom_id.rules "$srcdir" 644 0

for _bin in awk /usr/lib/udev/cdrom_id blockdev losetup; do
    copy_binary "$_bin"
done
