#!/bin/sh -e

cleanup()
{
    rm -rf "$DEST/usr/share/bash-completion" \
           "$DEST/usr/share/applications" \
           "$DEST/etc/bash_completion.d" \
           "$DEST/usr/lib/charset.alias" \
           "$DEST/usr/share/polkit-1" \
           "$DEST/usr/share/gettext" \
           "$DEST/usr/share/gtk-doc" \
           "$DEST/usr/share/locale" \
           "$DEST/usr/share/sounds" \
           "$DEST/usr/share/icons" \
           "$DEST/usr/share/info" \
           "$DEST/usr/share/doc" \
           "$DEST/usr/share/man" \
           "$DEST/usr/share/zsh"
}

case $TYPE in
    pre-build)
        case $PKG in
            linux)
                # kde sed -i 's@/sbin/hotplug@/usr/bin/helper@g' .config
            ;;
        esac
    ;;
    post-build)
        case $PKG in
            baselayout) # ensure we keep layout as is
                echo root:root | chpasswd --root "$DEST" root

                cp /root/.cache/issue "$DEST/etc/issue"
            ;;
            busybox)
                mkdir -p "$DEST/var/service"
                ln -sf /etc/sv/mdev "$DEST/var/service/mdev"

                # kde {
                # kde     echo 'SUBSYSTEM=drm;.*   root:video 660 *env > /tmp/.libudev-zero/uevent.\$\$'
                # kde     echo 'SUBSYSTEM=input;.* root:input 660 *env > /tmp/.libudev-zero/uevent.\$\$'
                # kde } >> "$DEST/etc/mdev.conf"

                cleanup
            ;;
            dbus)
                mkdir -p "$DEST/var/service"
                ln -sf /etc/sv/dbus "$DEST/var/service/dbus"

                cleanup
            ;;
            dhcpcd)
                mkdir -p "$DEST/var/service"
                ln -sf /usr/share/dhcpcd/hooks/10-wpa_supplicant "$DEST/usr/lib/dhcpcd/dhcpcd-hooks/10-wpa_supplicant"
                ln -sf /etc/sv/dhcpcd "$DEST/var/service/dhcpcd"
                
                cleanup
            ;;
            kiss) # ensure we keep docs
            ;;
            libudev-zero)
                cc contrib/helper.c -o helper
                install -Dm755 helper "$DEST/usr/bin/helper"

                cleanup
            ;;
            linux) # save around ~5M to iso disk
                mv "$DEST/boot/vmlinuz" /boot/vmlinuz

                cleanup
            ;;
            plasma-desktop)
                mkdir -p "$DEST/root/.local/share/bin"
                cp /root/.cache/profile "$DEST/root/.profile"
                cp /root/.cache/x       "$DEST/root/.local/share/bin/x"

                cleanup
            ;;
            *)
                cleanup
            ;;
        esac
    ;;
    post-install)
        case $PKG in
            plasma-desktop)
                rm -rf /root/.profile
            ;;
            util-linux)
                kiss a util-linux /usr/bin/mount
            ;;
        esac
    ;;
esac
