#!/bin/sh -e

case $TYPE in
    post-build)
        case $PKG in
            kiss) # ensure we keep docs
            ;;
            *)
                rm -rf "$DEST/usr/share/bash-completion" \
                       "$DEST/usr/share/applications" \
                       "$DEST/etc/bash_completion.d" \
                       "$DEST/usr/lib/charset.alias" \
                       "$DEST/usr/share/polkit-1" \
                       "$DEST/usr/share/gettext" \
                       "$DEST/usr/share/gtk-doc" \
                       "$DEST/usr/share/locale" \
                       "$DEST/usr/share/sounds" \
                       "$DEST/usr/share/icons" \
                       "$DEST/usr/share/info" \
                       "$DEST/usr/share/doc" \
                       "$DEST/usr/share/man" \
                       "$DEST/usr/share/zsh"
            ;;
        esac
    ;;
    post-install)
        case $PKG in
            util-linux)
                kiss a util-linux /usr/bin/mount
            ;;
        esac
     ;;
esac
