#!/bin/sh -e

make olddefconfig
#make kvm_guest.config
make -j "$(nproc)"
make INSTALL_MOD_PATH="$1/usr" INSTALL_MOD_STRIP=1 modules_install

rm "$1/usr/lib/modules/$2/build" "$1/usr/lib/modules/$2/source"

install -Dm644 "arch/x86/boot/bzImage" "$1/boot/vmlinuz"
