name: Shellcheck

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run shellcheck.
      run: |
        shopt -s nullglob
        shellcheck kiss-live run-qemu hooks/* repo/*/build repo/*/post-install repo/*/pre-remove
